language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSID
  secret_access_key:
    secure: $ACCESSSECRET
  region: "us-east-1"  
  app: "node-project"
  env: "NodeProject-env"
  bucket_name: "deploy-gabriel"
  on:
    branch: master
